language:
  - python
python:
  - '2.7'

install:
  - python setup.py test
  - pip install coveralls

script:
  - coverage run --source=snakebite setup.py nosetests
  - python setup.py flake8

after_success:
  coveralls

notifications:
  email:
  - kelvintaywl@gmail.com